### PR TITLE
Numpy interface for BulkRead

### PR DESCRIPTION
**Pull request by jpivarski**
This is everything that was demonstrated at

https://indico.cern.ch/event/658069/

### CODE REVIEW

**Comment by jpivarski** [comment]
I've just verified that this pull request has my new changes, in which I took out 780 LoC and added 60 LoC. It's weird how GitHub pull requests are a moving target, collecting commits until the pull-requestee clicks "merge," rather than freezing it at a particular commit and requiring the pull-requestor to close and submit a new pull request. It's a very un-git-like design.

Anyway, this is the pull request as I'd like it to be merged _now._ (It's a pity to see all that work go away, but I know which version _I'd_ want to maintain.) I don't foresee any/many changes to the C++, but I do still need to add tests and a high-level interface over this low-level routine.

If you approve this pull request and then forward it as a pull request to the main ROOT repository, I can start making pull requests centrally and won't have to bother you with these.  `:)`  The only issues you might want to be in the loop on are:

   * What's the future of `GetDeserializeType`? Should we disable the check, as I have here, or set the flag on all the appropriate `TLeaf` types?
   * Maybe some insights when I have more detailed results on the read-rate slow-down (225 MB/s → 1 MB/s in `GetEntriesSerialized`).

**Comment by jpivarski** [comment]
The "files changed" tab is now readably short. You can see that I added some Python stuff in the appropriate places and removed your checks on `GetDeserializeType`, and nothing else.

**Comment by bbockelm** [comment]
@jpivarski - I'm ready to come back to this.  I think we're ready to merge - any remaining TODO items?

**Comment by jpivarski** [comment]
Even though you merged up to Friday, this pull request was never closed (in GitHub; I assume you used git directly). The last changes before we send a pull request to the main ROOT repository have now been applied. Specifically, I've finished these tasks:

   * Refactor GetEntriesFast and GetEntriesSerialized so that common code calls a common private method.
   * Remove all references to TLeaf::ReadBasketSerialized.
   * Get my bug-fixes from Friday in the same PR.

There are no tests yet, but I want to do that as a separate pull request.

Unless you see anything else to clean up, let's merge this into your fork and submit it to ROOT:master!

**Pull request merged**
